### ISSUE TITLE
Handle `Live chat is no longer live` error from the youtube api

### ISSUE THREAD

**Issue by benhoff** [benhoff/vexbot#14]
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/hoff/swdev/vexbot/vexbot/adapters/youtube_api.py", line 144, in _recv_loop
    livechat_response = youtube_api.liveChatMessages().list(liveChatId=live_chat_id, part=part, pageToken=next_token).execute()
  File "/home/hoff/swdev/vexbot/env/lib/python3.5/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/home/hoff/swdev/vexbot/env/lib/python3.5/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/youtube/v3/liveChat/messages?alt=json&liveChatId=Cg0KC3c4U2VZa1FGMDNJ&part=snippet%2C+authorDetails&pageToken=GK_ynav8tc4CIKmcwc7_tc4C returned "The live chat is no longer live.">

**Comment by IHateNameStealers** [comment]
About to start playing with your Vexbot. I would like to use it with YouTube.
Does it still work with YT?

**Comment by benhoff** [comment]
The core logic is sound, but I believe the bot itself is slightly broken.
I haven't had time to get it running again

**Comment by IHateNameStealers** [comment]
That's to bad. I'm afraid that with my coding skills I'm not able to fix this :-(
